const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");
const fetch = require("node-fetch");
module.exports = {
	data: new SlashCommandBuilder()
		.setName("cat")
		.setDescription("Grabs a random cat off the internet."),
	async execute(interaction) {
		const responce = await fetch("https://api.thecatapi.com/v1/images/search");
		const data = await responce.json();
		if (data) {
			const embed = new EmbedBuilder()
				.setColor("#ff6633")
        .setTitle("Kitty")
        .setDescription("Random Cat " + data.id)
        .setImage(data.url)
        .setTimestamp()
				.setFooter({
          text: "Generated By SuperNova",
          iconURL: client.images.pfp,
        });
			try {
				await interaction.reply({ embeds: [embed ]});
			} catch (err) {
				await interaction.reply(`${client.emotes.think} Could not gather details.....`);
			}
		}
	}
}
