const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");
const fetch = require("node-fetch");
module.exports = {
	data: new SlashCommandBuilder()
		.setName("dog")
		.setDescription("Grabs a random dog off the internet."),
	async execute(interaction) {
		const responce = await fetch("https://dog.ceo/api/breeds/image/random");
		const data = await responce.json();
		if (data) {
			const embed = new EmbedBuilder()
				.setColor("#ff6633")
        .setTitle("Doggy")
        .setDescription("Random Dog.")
        .setImage(data.message)
        .setTimestamp()
				.setFooter({
          text: "Generated By SuperNova",
          iconURL: client.images.pfp,
        });
			try {
				await interaction.reply({ embeds: [embed ]});
			} catch (err) {
				await interaction.reply(`${client.emotes.think} Could not gather details.....`);
			}
		}
	}
}
