const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('invite')
		.setDescription('Sends the bots invite link.'),
	async execute(interaction) {
		const embed = new EmbedBuilder()
            		.setColor('#ff6633')
            		.setTitle("Invite")
            		.setDescription('Invite our Bot using https://tinyurl.com/applabinvite')
            		.setTimestamp()
							.setFooter({ text: 'Generated By Applab', iconURL: 'https://code.org/images/app-lab/applab-tool.png' });

		try {
				await interaction.reply({
					embeds: [embed]
				});
			} catch (err) {
				await interaction.reply(`Could not gather project details.....`);
			}
	},
};
