const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");

module.exports = {
  data: new SlashCommandBuilder()
    .setName("invite")
    .setDescription("Sends the bots invite link."),
  async execute(interaction) {
    const embed = new EmbedBuilder()
      .setColor("#ff6633")
      .setTitle("Invite")
      .setDescription(
        "Invite our Bot using https://tinyurl.com/supernovainvite"
      )
      .setTimestamp()
      .setFooter({
        text: "Generated By SuperNova",
        iconURL: client.images.pfp,
      });

    try {
      await interaction.reply({
        embeds: [embed],
      });
    } catch (err) {
      await interaction.reply(
        `${client.emotes.think} Could not gather details.....`
      );
    }
  },
};
