const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");

module.exports = {
  data: new SlashCommandBuilder()
    .setName("invite")
    .setDescription("Sends the bots invite link."),
  async execute(interaction) {
    const embed = new EmbedBuilder()
      .setColor("#ff6633")
      .setTitle("Invite")
      .setDescription(
        "Invite our Bot using https://tinyurl.com/supernovainvite"
      )
      .setTimestamp()
      .setFooter({
        text: "Generated By SuperNova",
        iconURL:
          "https://github.com/Colack/SuperNova/blob/main/assets/Colack_SuperNova_exploding_in_the_background_meteor_shower_rain_3fc39dec-c581-4141-a73d-dcb95138a4db.png?raw=true",
      });

    try {
      await interaction.reply({
        embeds: [embed],
      });
    } catch (err) {
      await interaction.reply(
        `${client.emotes.think} Could not gather project details.....`
      );
    }
  },
};
