const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");
const fetch = require("node-fetch");
module.exports = {
  data: new SlashCommandBuilder()
    .setName("meme")
    .setDescription("Sends a random meme off the internet!"),
  async execute(interaction) {
    const responce = await fetch("https://meme-api.herokuapp.com/gimme");
    const data = await responce.json();
    if (data) {
      const embed = new EmbedBuilder()
        .setColor("#ff6633")
        .setTitle(data.title)
        .setDescription("Author: " + data.author)
        .setImage(data.url)
        .setTimestamp()
        .setFooter({
          text: "Generated By SuperNova",
          iconURL:
            "https://github.com/Colack/SuperNova/blob/main/assets/Colack_SuperNova_exploding_in_the_background_meteor_shower_rain_3fc39dec-c581-4141-a73d-dcb95138a4db.png?raw=true",
        });
      try {
        await interaction.reply({ embeds: [embed] });
      } catch (err) {
        await interaction.reply(
          `${client.emotes.think} Could not gather project details.....`
        );
      }
    }
  },
};
